sudo: required

dist: trusty

language: generic

services:
  - docker

matrix:
  fast_finish: true

install:
  - chmod +x ci.sh && ./ci.sh install

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.5.2
    - NODE_VERSION=0.10.43
    - ROOT_URL=http://0.0.0.0:3000/
  matrix:
    - CMD=test
    - CMD=build

script: ./ci.sh $CMD
