sudo: required

dist: trusty

language: node_js

node_js:
  - '5'

services:
  - docker

matrix:
  fast_finish: true

install:
  - chmod +x ci.sh && ./ci.sh install

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.5.2
    - ROOT_URL=http://0.0.0.0:3000/
    - SAUCE_USERNAME=albertzak-rslnd
    - SAUCE_HOST=ondemand.saucelabs.com
    - SAUCE_PORT=80
    - secure: "qnQ7/1I/gRH1rCklbJVYfMKL4bdKSWDHNMzI0Rq2GdTNtL2QnWvLPD3Yqy9wg9c/H14j973Fo1Uvilq3F/YJmxowNHJrPC9g859S0YlLaUFm374OLGNKAYjk9+A4FpvDj037yFtdzH/p0FUKqom9Gfn+UMG/iGH1Xny/YBbrrCZTLFkONsmdmyF6m3tMiLSlFrUzo6fEmY08OuLeRuPn5sfrPlXEyEFRegtEz+StmlmtqvMW0zqguSOMAMWaO7Nokvgt8uQTtX3rt/AJgPP9wPgDrvAZQjfzs0TE3G0CLIeQDgG9y5jrtSbycK6Ef0tZhz5zu1hbMvpz+1Vg7CXawc98loOWq/erDIle5VqG8rT9IQ77248CZoiMOPpFz27o2lT3cZlH4o5HlejeT5SUHuDjXMmf5V/EmpVbJBgIuT+FdWBB/wliV0t+RX4njnosPmYiTY9arTljVy0SyyPQc/DWQPfPqzJR9ZUVmIe4oIYmsEQULIDXrhNQvNvPxHmVQoG6Qj9zNzTLCk+3CpVVhTDM2l9JZv9HrwU+pYLmKIeEFdoRSSmXHmhT95bsIJRhYoffz4wzv078Un4Oy8leXnAmDpb1fbGH34Zv7LCyAFTvtX2eS/EWOClZlLChzXwGfCeeUDZoIcraOdR0gLk7XbEtUm5U6tErE+6Bg+4eSfs="

  matrix:
    - CMD=build
    - CMD=test   OS='Windows 10'   BROWSER=chrome:beta
    - CMD=test   OS='Windows 8'    BROWSER=internetexplorer:10.0
    - CMD=test   OS='Windows 7'    BROWSER=internetexplorer:11.0
    - CMD=test   OS='Windows 7'    BROWSER=firefox:36.0
    - CMD=test   OS='Windows XP'   BROWSER=chrome:39.0

script: ./ci.sh $CMD

addons:
  sauce_connect: true
