sudo: required

dist: trusty

language: node_js

node_js:
  - '4.4.4'

services:
  - docker

matrix:
  fast_finish: true

install:
  - chmod +x ci.sh && ./ci.sh install

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.5.2
    - ROOT_URL=http://0.0.0.0:3000/

  matrix:
    - CMD=build
    - CMD=test   OS='Windows 10'   BROWSER='Chrome:50.0'

script: ./ci.sh $CMD

after_script: echo "leader=$BUILD_LEADER status=$BUILD_AGGREGATE_STATUS"

after_success: ./ci.sh after_success

after_failure: ./ci.sh after_failure

addons:
  sauce_connect: true
