sudo: required

dist: trusty

language: node_js

services:
  - docker

node_js:
  - '0.12'

before_install:
  - '/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16'
  - npm install
  - cd app/meteor/tests/cucumber && npm install && cd ../../../../

cache:
  directories:
    - 'node_modules'
    - 'app/meteor/tests/cucumber/node_modules'
    - '~/.npm'

before_script:
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
  - sleep 3
  - chmod +x environments/production/build.sh
  - cd environments/development/
  - docker-compose pull
  - docker-compose run meteor meteor npm install
  - docker-compose up &
  - cd ../../
  - for i in {1..60}; do curl "http://0.0.0.0:3000" && break; sleep 10; done;

env:
  global:
    - ROOT_URL=http://0.0.0.0:3000/
  matrix:
    - CMD="npm test"
    - CMD=environments/production/build.sh

script: $CMD
