sudo: required

dist: trusty

language: node_js

services:
  - docker

node_js:
  - '0.12'

before_install:
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16
  - npm install
  - cd app/meteor/tests/cucumber && npm install && cd ../../../../

cache:
  directories:
    - node_modules
    - app/meteor/tests/cucumber/node_modules
    - app/meteor/.meteor/local
    - app/meteor/npm_modules
    - ~/.npm

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - chmod +x production/build.sh
  - docker-compose -f docker-compose.yml -f docker-compose.test.yml pull
  - docker-compose -f docker-compose.yml -f docker-compose.test.yml run meteor meteor npm install
  - npm run start:test &
  - cd ../../
  - for i in {1..60}; do curl 'http://0.0.0.0:3000' && break; sleep 10; done;

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.5.2
    - ROOT_URL=http://0.0.0.0:3000/
  matrix:
    - CMD='npm test'
    - CMD=production/build.sh

script: $CMD
