# Travis CI builds the native apps (Electron)

sudo: required
language: node_js
node_js:
  - "0.12"

cache:
  directories:
    - ~/.npm
    - node_modules
    - app/electron/node_modules

before_install:
   # Wine and Mono for building Windows installers
  - sudo add-apt-repository ppa:ubuntu-wine/ppa -y
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
  - echo "deb http://download.mono-project.com/repo/debian wheezy-libtiff-compat main" | sudo tee -a /etc/apt/sources.list.d/mono-xamarin.list
  - sudo apt-get -qq update
  - sudo apt-get -qq install wine mono-devel -y

  - npm install
  - cd ./app/electron/; npm install --dev; cd -;

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - cd ./app/electron/; grunt build;
