sudo: required

dist: trusty

language: node_js

node_js:
  - '4.5.0'

services:
  - docker

matrix:
  fast_finish: true

install:
  - echo "54.192.225.217 warehouse.meteor.com" | sudo tee -a /etc/hosts
  - sudo curl --output /usr/local/phantomjs/phantomjs https://s3.amazonaws.com/circle-downloads/phantomjs-2.1.1
  - chmod +x ci.sh && ./ci.sh install

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.5.2
    - NPM_VERSION=3.10.7
    - NPM_CONFIG_LOGLEVEL=warn
    - ROOT_URL=http://0.0.0.0:3000/
    - PHANTOMJS_CDNURL=http://cnpmjs.org/downloads

  matrix:
    - CMD=build
    - CMD=test   OS='Windows 10'   BROWSER='Chrome:50.0'

script: ./ci.sh $CMD

after_success: ./ci.sh after_success

after_failure: ./ci.sh after_failure

addons:
  sauce_connect: true
  no_ssl_bump_domains: all

notifications:
  slack:
    secure: RaBq7GOQxyEeEHfJg22qFqQovAMCSc1cKdpSizodVfBVSzm1iRAYB5eXpMl3wYiyi/+vT2VbLFBJMpZQnn+oRdB/q1VXGgEHlX9zcTBEkfUPkp3vCZATxMRuSj8NP1uVDWA0HZZgabX/yGXr8Q/6FTWFV/XYElO+7w8UVmtPvfdjHxDJm6c0Q2UjkGHEOlwtApBUbT+IPFOoBp2dd8JLVUTVbL19PrsvOPUh93KfIqP4uew2EEBQFArNR22/c3YCKtsXYgx3RVQc0jCZfLlEkXiJcZZVwanYUczBVbIOIYHeNlcoCHjL8iMLq003Xp6Gw3IlgwapzeGvO55sW9qOv/XFXTWQWKBdp40VegzoxnU0svMpx99g6wxtqHuRD/22Fv0hat1lQnVHgZwgh0XvBcDk0jLRW1FbpV37oRDSMiAMq1KnVlkvsYcTGWsMvrGDMaHBE6xABHdJpcYwRZTxV5DMnci5FSEcx5ieg0tCDAMuk6He3BgofvKmaV1W50JE/bBCseB/LN0Z1PUBl0pjdXEwovnt8iCg02CnYywAaVkFPjaMnVWzwpDSj9U+jELQpSIqKzBdoS0rlhC01hC4ymS+CA6BAzH86PutCh+BcXEyYOzhQBP1qxgQuuN9am1VXtd7ckGgK4AWyf57LzSy542IUNjbxYrykzGjjeK2Fuk=
