version: '{build}'

branches:
  only:
  - master

shallow_clone: true

environment:
  nodejs_version: '8.9.3'

install:
- ps: >-
    Install-Product node $env:nodejs_version

    choco install autoit.commandline

    choco install yarn

    echo "node version"

    node --version

- cmd: >-
    cd app\electron\

    yarn

build_script:
- ps: >-
    cmd /c 'npm run build 2>&1'
