version: '{build}'

branches:
  only:
  - master

shallow_clone: true

environment:
  nodejs_version: '12.13.0'

install:
- ps: >-
    Install-Product node $env:nodejs_version

    choco install autoit.commandline

    choco install yarn

    echo "node version"

    node --version

- cmd: >-
    cd app\electron\

    yarn

build_script:
- ps: >-
    cmd /c 'yarn run compile 2>&1'

    cmd /c 'yarn run release 2>&1'
