version: '{build}'

branches:
  only:
  - master

shallow_clone: true

environment:
  nodejs_version: '8.9.3'

install:
- ps: >-
    Install-Product node $env:nodejs_version

    echo "node version"

    node --version

    echo "npm version"

    npm --version

- cmd: >-
    cd app\electron\

    npm i

build_script:
- ps: >-
    $package = Get-Content -Raw -Path package.json | out-string | ConvertFrom-Json


    $env:ROSALIND_VERSION = "v" + $package.version


    cmd /c 'npm run client:build 2>&1'

test_script:
- ps: >-
    echo "--> Installing app"


    & ".\build\installer\Rosalind-win32-ia32\RosalindSetup-win-$env:ROSALIND_VERSION.exe"
    & ".\build\installer\Rosalind-win32-ia64\RosalindSetup-win-$env:ROSALIND_VERSION.exe"


    Start-Sleep -s 30

    taskkill /F /IM Rosalind.exe



    echo "--> Launching app"


    & Start-Process -Wait -ArgumentList --debug-quit-on-ready "$env:UserProfile\Desktop\Rosalind.lnk"


    echo "--> Done"

artifacts:
- path: app\electron\build\installer\Rosalind-win32-ia32\RELEASES
  name: RELEASES-win-ia32
- path: app\electron\build\installer\Rosalind-win32-ia32\*.exe
  name: RosalindSetup-win-ia32.exe
- path: app\electron\build\installer\Rosalind-win32-ia32\*.nupkg
  name: rosalind-win-ia32.nupkg
- path: app\electron\build\installer\Rosalind-win32-ia64\RELEASES
  name: RELEASES-win-ia64
- path: app\electron\build\installer\Rosalind-win32-ia64\*.exe
  name: RosalindSetup-win-ia64.exe
- path: app\electron\build\installer\Rosalind-win32-ia64\*.nupkg
  name: rosalind-win-ia64.nupkg


deploy:
- provider: GitHub
  tag: $(ROSALIND_VERSION)
  release: $(ROSALIND_VERSION)
  description: "🐣 Rosalind Client, Windows $(ROSALIND_VERSION)"
  auth_token:
    secure: PHADmhUgXdLiPP7KA7E+MqiX/CV9DMyoDfvFP+0pyzXfozFC0tiQ2QfdzlPEVU69
  artifact: RosalindSetup-win-ia32.msi,RosalindSetup-win-ia32.exe,RELEASES-win-ia32,rosalind-win-ia32.nupkg,RosalindSetup-win-ia64.msi,RosalindSetup-win-ia64.exe,RELEASES-win-ia64,rosalind-win-ia64.nupkg
  force_update: true
