meteor:
  restart: on-failure:10

storybook:
  image: quay.io/rosalind/meteor-development:1.3.5.1
  command: ./node_modules/.bin/start-storybook -p 3001
  ports:
    - '3001:3001'
  volumes:
    - ./app/meteor:/app
    - /root/.npm

kibana:
  image: seeruk/docker-kibana-sense
  ports:
    - '5601:5601'
  links:
    - elasticsearch

mongodb:
  ports:
    - '27017:27017'
