meteor:
  image: quay.io/rosalind/meteor-development:1.3.3
  command: meteor
  restart: on-failure:10
  ports:
    - '3000:3000'
  volumes:
    - ./app/meteor:/app
    - ./build:/build
    - /root/.npm
  environment:
    - NODE_ENV=development

kibana:
  image: seeruk/docker-kibana-sense
  ports:
    - '5601:5601'
  links:
    - elasticsearch

mongodb:
  ports:
    - '27017:27017'
