meteor:
  image: quay.io/rosalind/meteor-development:1.3.2.4
  working_dir: /rosalind/app/meteor
  command: meteor
  restart: on-failure:10
  ports:
    - '3000:3000'
  volumes:
    - .:/rosalind
  environment:
    - NODE_ENV=development
    - METEOR_WATCH_FORCE_POLLING=t
    - METEOR_WATCH_POLLING_INTERVAL_MS=1500

kibana:
  image: seeruk/docker-kibana-sense
  ports:
    - '5601:5601'
  links:
    - elasticsearch

mongo-admin:
  image: knickers/mongo-express
  ports:
    - '8081:8081'
  environment:
    - ME_CONFIG_MONGODB_SERVER=mongodb
  links:
    - mongodb

mongodb:
  ports:
    - '27017:27017'
