meteor:
  image: quay.io/rosalind/meteor-development:1.3.3-3
  command: meteor
  ports:
    - '3000:3000'
  environment:
    - NODE_ENV=development
    - MONGO_URL=mongodb://mongodb:27017/rosalind
    - ELASTICSEARCH_URL=http://elasticsearch:9200
    - ROOT_URL=http://0.0.0.0:3000
    - 'CUSTOMER_NAME=Rosalind Development'
  volumes:
    - ./app/meteor:/app
    - ./build:/build
    - /root/.npm
  links:
    - mongodb
    - elasticsearch
    - transporter

transporter:
  image: quay.io/rosalind/mongo2es:latest
  environment:
    - M2E_DESTINATION=http://elasticsearch:9200
    - M2E_NAMESPACE=rosalind.patients
    - M2E_SOURCE=mongodb://mongodb
  links:
    - elasticsearch
    - mongodb

elasticsearch:
  image: quay.io/rosalind/elasticsearch-phonetic:2.2.0

mongodb:
  image: mvertes/alpine-mongo:3.2.3
