meteor:
  build: .
  ports:
    - "3000:3000"
  volumes:
    - .:/app/
  environment:
    - MONGO_URL=mongodb://mongodb:27017/rosalind
    - ELASTICSEARCH_URL=http://elasticsearch:9200
    - ROOT_URL=http://0.0.0.0:3000
  links:
    - mongodb
    - elasticsearch

mongodb:
  image: mongo:latest
  restart: always
  ports:
    - "27017"
  volumes_from:
    - persist

elasticsearch:
  image: liquidautumn/elasticsearch-phonetic
  restart: always
  ports:
    - "9200"
    - "9300"
  volumes_from:
    - persist

persist:
  image: busybox
