nodes:
  patientsSource:
    type: mongo
    uri: mongodb://mongodb/rosalind
    namespace: 'rosalind.patients'
    bulk: true

  patientsDestination:
    type: elasticsearch
    uri: http://elasticsearch:9200/rosalind
    namespace: 'rosalind.patients'
