version: 2.1
jobs:
  build:
    machine:
      image: 'ubuntu-2204:2022.10.2'
    resource_class: large
    steps:
      - checkout
      - run: chmod +x ci.sh && ./ci.sh install
      - run: ./ci.sh test
      - run: ./ci.sh build
