version: 2.1
jobs:
  build:
    machine:
      image: 'cimg/base:2022.11'
    resource_class: large
    steps:
      - checkout
      - run: chmod +x ci.sh && ./ci.sh install
      - run: ./ci.sh test
      - run: ./ci.sh build
