version: 2.1
jobs:
  build:
    machine:
      image: 'ubuntu-2004:202010-01'
    steps:
      - checkout
      - run: chmod +x ci.sh && ./ci.sh install
      - run: ./ci.sh test
      - run: ./ci.sh build
