meteor:
  image: quay.io/rosalind/meteor-development:1.3.1
  command: meteor
  restart: on-failure:10
  ports:
    - '3000:3000'
  volumes:
    - ../../app/meteor:/app/
  environment:
    - NODE_ENV=development
    - MONGO_URL=mongodb://mongodb:27017/rosalind
    - ELASTICSEARCH_URL=http://elasticsearch:9200
    - ROOT_URL=http://0.0.0.0:3000
    - CUSTOMER_NAME=
    - METEOR_WATCH_FORCE_POLLING=t
    - METEOR_WATCH_POLLING_INTERVAL_MS=1500
  links:
    - mongodb
    - elasticsearch
    - transporter

kibana:
  image: seeruk/docker-kibana-sense
  ports:
    - '5601:5601'
  links:
    - elasticsearch

mongo-admin:
  image: knickers/mongo-express
  ports:
    - '8081:8081'
  environment:
    - ME_CONFIG_MONGODB_SERVER=mongodb
  links:
    - mongodb

transporter:
  image: quay.io/rosalind/mongo2es:latest
  environment:
    - M2E_DESTINATION=http://elasticsearch:9200
    - M2E_NAMESPACE=rosalind.patients
    - M2E_SOURCE=mongodb://mongodb
  links:
    - elasticsearch
    - mongodb

elasticsearch:
  image: quay.io/rosalind/elasticsearch-phonetic:latest

mongodb:
  image: mongo:latest
  ports:
    - '27017:27017'
