meteor:
  build: .
  command: meteor --settings settings.json
  ports:
    - '3000:3000'
  volumes:
    - ../../app/meteor:/app/
  environment:
    - NODE_ENV=development
    - MONGO_URL=mongodb://mongodb:27017/rosalind
    - ELASTICSEARCH_URL=http://elasticsearch:9200
    - ROOT_URL=http://0.0.0.0:3000
  links:
    - mongodb
    - elasticsearch
    - transporter

kibana:
  image: seeruk/docker-kibana-sense
  ports:
    - '5601:5601'
  links:
    - elasticsearch

mongo-admin:
  image: knickers/mongo-express
  ports:
    - '8081:8081'
  environment:
    - ME_CONFIG_MONGODB_SERVER=mongodb
  links:
    - mongodb

transporter:
  image: quay.io/rosalind/mongo2es:latest
  environment:
    - M2E_DESTINATION=http://elasticsearch:9200
    - M2E_NAMESPACE=rosalind.patients
    - M2E_SOURCE=mongodb://mongodb
  links:
    - elasticsearch
    - mongodb
  restart: always

elasticsearch:
  image: quay.io/rosalind/elasticsearch-phonetic:latest
  restart: always

mongodb:
  image: 'mongo:latest'
  restart: always
  ports:
    - '27017:27017'
