mongodb:
  image: mongo:latest
  restart: always
  ports:
    - "27017:27017"
  volumes_from:
    - persist

elasticsearch:
  image: liquidautumn/elasticsearch-phonetic
  restart: always
  ports:
    - "9200:9200"
    - "9300:9300"
  volumes_from:
    - persist

persist:
  image: busybox
