version: '2.1'

services:
  minio:
    image: 'minio/minio:RELEASE.2020-07-13T18-09-56Z'
    command: 'server /data'
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_REGION=${MINIO_REGION}
    ports:
      - '9000:9000'
    volumes:
      - './minio-data:/data'
    links:
      - broker

  # minio-config:
  #   image: minio/mc
  #   links:
  #     - minio
  #   restart: on-failure
  #   environment:
  #     - MINIO_HOST=minio
  #     - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
  #     - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
  #     - MINIO_REGION=${MINIO_REGION}
  #     - SOURCE_BUCKET=hzw-media-uploads
  #     - TARGET_BUCKET=hzw-media
  #     - MINIO_NOTIFY_MQTT_ENABLE=on
  #     - MINIO_NOTIFY_MQTT_BROKER=tcp://broker:1883
  #     - MINIO_NOTIFY_MQTT_TOPIC=minio
  #     - MINIO_NOTIFY_MQTT_QOS=2
  #   entrypoint: >
  #     /bin/sh -c "
  #       echo Waiting for minio service to start...;
  #       while ! nc -z minio 9000;
  #       do
  #         sleep 1;
  #       done;
  #       echo Connected!;
  #       mc mb hzw-media-uploads;
  #       mc mb hzw-media;
  #       mc admin config set local notify_mqtt:1
  #       mc admin config get
  #       exit 0;
  #     "

  optimizer:
    build: './optimizer'
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_REGION=${MINIO_REGION}
      - MINIO_HOST=minio
      - SOURCE_BUCKET=hzw-media-uploads
      - TARGET_BUCKET=hzw-media
      - MQTT_BROKER=tcp://broker:1883
      - MQTT_TOPIC=minio
    links:
      - broker
      - minio

  broker:
    image: eclipse-mosquitto:latest


  # mirror-up:
  #   image: 'minio/mc'
  #   command: 'mirror --watch minio/minio-test-replication s3/minio-test-replication'
  #   volumes:
  #     - './mc.config.json:/root/.mc/config.json'
  #   depends_on:
  #     minio:
  #       condition: service_healthy

  # mirror-down:
  #   image: 'minio/mc'
  #   entrypoint: '/mirror-down.sh'
  #   volumes:
  #     - './mc.config.json:/root/.mc/config.json'
  #     - './mirror-down.sh:/mirror-down.sh'
  #   depends_on:
  #     minio:
  #       condition: service_healthy
